// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbamROwXD6GAucd1IBKyQJxB-mYZlREuQ',
    appId: '1:929169864387:web:6756910eed6a6cf2dc9476',
    messagingSenderId: '929169864387',
    projectId: 'tasks-b5b84',
    authDomain: 'tasks-b5b84.firebaseapp.com',
    storageBucket: 'tasks-b5b84.appspot.com',
    measurementId: 'G-VMY17HQKQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASoW9CIrNNKW5kajyLDlnkGPuheY_DYS0',
    appId: '1:929169864387:android:db40b649f9aaa4f3dc9476',
    messagingSenderId: '929169864387',
    projectId: 'tasks-b5b84',
    storageBucket: 'tasks-b5b84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANJu9YuqiUPJIGKvUPRCDUQFRcVXpLzyw',
    appId: '1:929169864387:ios:65bf83e99a7d7f49dc9476',
    messagingSenderId: '929169864387',
    projectId: 'tasks-b5b84',
    storageBucket: 'tasks-b5b84.appspot.com',
    iosBundleId: 'com.example.tasksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANJu9YuqiUPJIGKvUPRCDUQFRcVXpLzyw',
    appId: '1:929169864387:ios:4297503c0842aa8edc9476',
    messagingSenderId: '929169864387',
    projectId: 'tasks-b5b84',
    storageBucket: 'tasks-b5b84.appspot.com',
    iosBundleId: 'com.example.tasksApp.RunnerTests',
  );
}
